# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 13:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='acadCalendarioAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='acadCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='acadHorarioTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(blank=True, max_length=16, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='acadHorarioTurnoHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField(blank=True, null=True)),
                ('fin', models.TimeField(blank=True, null=True)),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
                ('horarioturno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.acadHorarioTurno')),
            ],
        ),
        migrations.CreateModel(
            name='acadModalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='acadNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='acadOfertaAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='acadPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='icpnaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20)),
                ('is_nuevo', models.BooleanField(default=True)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('pago_duplicado', models.BooleanField()),
                ('fecha_duplicado', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=150, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='icpnaDocente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('workstation_name', models.CharField(blank=True, max_length=150, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='icpnaMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.icpnaAlumno')),
            ],
        ),
        migrations.CreateModel(
            name='icpnaPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=250, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=250, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=250, null=True)),
                ('nombres', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_documento', models.CharField(choices=[('1', 'DNI'), ('2', 'CE')], default='DNI', max_length=1)),
                ('nro_documento', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ubigeo', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('referencia_direccion', models.TextField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=1, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('grado_academico', models.CharField(blank=True, max_length=1, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('img_documento', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='icpnaTelefonoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=250, null=True)),
                ('operador', models.CharField(choices=[('1', 'MOVISTAR'), ('2', 'CLARO'), ('3', 'BITEL'), ('4', 'ENTEL')], default=1, max_length=1)),
                ('descriptor', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='icpnaUbigeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=2)),
                ('distrito', models.CharField(max_length=2)),
                ('provincia', models.CharField(max_length=2)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='instAmbiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('capacidad_adicional', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('is_aula', models.NullBooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='instInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=250, null=True)),
                ('direccion_fiscal', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('ruc', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='instLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=6, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
                ('institucion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion')),
            ],
        ),
        migrations.CreateModel(
            name='instSede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.TextField(blank=True, null=True)),
                ('workstation_ip', models.TextField(blank=True, null=True)),
                ('institucion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='instlocal',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='instlocal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instambiente',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='instambiente',
            name='local_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instLocal'),
        ),
        migrations.AddField(
            model_name='instambiente',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='instambiente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icpnatelefonopersona',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='icpnatelefonopersona',
            name='persona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.icpnaPersona'),
        ),
        migrations.AddField(
            model_name='icpnatelefonopersona',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='icpnapersona',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='icpnapersona',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='icpnapersona',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icpnamatricula',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='icpnamatricula',
            name='ofertaacademica_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.acadOfertaAcademica'),
        ),
        migrations.AddField(
            model_name='icpnamatricula',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='icpnamatricula',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icpnadocente',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='icpnadocente',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='icpnaalumno',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='icpnaalumno',
            name='persona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.icpnaPersona'),
        ),
        migrations.AddField(
            model_name='icpnaalumno',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='acadprograma',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='acadprograma',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='acadprograma',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acadofertaacademica',
            name='ambiente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instAmbiente'),
        ),
        migrations.AddField(
            model_name='acadofertaacademica',
            name='calendarioacademica_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.acadCalendarioAcademica'),
        ),
        migrations.AddField(
            model_name='acadofertaacademica',
            name='curso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.acadCurso'),
        ),
        migrations.AddField(
            model_name='acadofertaacademica',
            name='docente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.icpnaDocente'),
        ),
        migrations.AddField(
            model_name='acadofertaacademica',
            name='horarioturno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.acadHorarioTurno'),
        ),
        migrations.AddField(
            model_name='acadofertaacademica',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='acadofertaacademica',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='acadnivel',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='acadnivel',
            name='programa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.acadPrograma'),
        ),
        migrations.AddField(
            model_name='acadnivel',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='acadnivel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acadmodalidad',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='acadmodalidad',
            name='programa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.acadPrograma'),
        ),
        migrations.AddField(
            model_name='acadmodalidad',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='acadmodalidad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acadhorarioturnohoras',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='acadhorarioturnohoras',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='acadhorarioturnohoras',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acadhorarioturno',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='acadhorarioturno',
            name='modalidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.acadModalidad'),
        ),
        migrations.AddField(
            model_name='acadhorarioturno',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='acadhorarioturno',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acadcurso',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='acadcurso',
            name='nivel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.acadNivel'),
        ),
        migrations.AddField(
            model_name='acadcurso',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='acadcurso',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acadcalendarioacademica',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instInstitucion'),
        ),
        migrations.AddField(
            model_name='acadcalendarioacademica',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instSede'),
        ),
        migrations.AddField(
            model_name='acadcalendarioacademica',
            name='user',
            field=models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
