# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acadofertaacademica',
            name='horarioturnohoras_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.acadHorarioTurnoHoras'),
        ),
    ]
