# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_icpnaasistenciadocente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icpnaasistenciadocente',
            name='ingreso_fecha',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='icpnaasistenciadocente',
            name='ingreso_hora',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='icpnaasistenciadocente',
            name='salida_fecha',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='icpnaasistenciadocente',
            name='salida_hora',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
