# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20160315_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icpnaasistenciadocente',
            name='salida_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icpnaasistenciadocente',
            name='salida_hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
