# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20160316_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icpnaasistenciadocente',
            name='ingreso_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icpnaasistenciadocente',
            name='ingreso_hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
